server:
  port: 8761
eureka:
  client:
   # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
   # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false


# eureka 高可用  集群   两个eureka注册中心服务器 互相注册   开启switchhosts！-My hosts
# edit configurations：Active profiles: eureka1 or eureka2
#spring:
#  application:
#    name: springcloud-eureka-center
#---
#spring:
#  profiles: eureka1                                 # 指定profile=eureka1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: eureka1                               # 指定当profile=eureka1，主机名是eureka2
#  client:
#    serviceUrl:
#      defaultZone: http://eureka2:8762/eureka/      # 将自己注册到eureka2这个Eureka上面去
#---
#spring:
#  profiles: eureka2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: eureka2
#  client:
#    serviceUrl:
#      defaultZone: http://eureka1:8761/eureka/