spring:
  application:
    # 指定注册到eureka server上的服务名称，对于用户微服务，本系列将名称设为springcloud-service-movie
    name: springcloud-service-movie-feign-hystrix
  jpa:
    # 显示SQL
    show-sql: true
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
server:
  port: 8702
management:
  endpoint:
    #健康检查  查看详情
    health:
      show-details: always
    #断路器监控
  endpoints:
    web:
      exposure:
        include: '*'
#给feign client 开启断路器 全局启用
feign:
  hystrix:
    enabled: true